### ISSUE TITLE
Get references to two NLP methods mentioned by Justin G.

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#1]
On Friday March 13, Justin G. mentioned two NLP methods that he would like Sage to deploy first in an EC2, then in an NCATS EC2. According to Justin, both method can be used using a CLI and web interface.

- [x] Find these two methods and list their resources (repos, documentation, papers, etc.)

**Comment by tschaffter** [comment]
On March 13, Yao shared the following information about two NLP methods.

# Method 1: Deidentification

**Short description:** Automated de-identification of protected health information from electronic health records.

**Repository:** https://bitbucket.org/MCW_BMI/notes-deidentification/src/master/

# Method 2: UCSFPhilter

**Short description:** Philter is a command-line based clinical text de-identification software that removes protected health information (PHI) from any plain text file.

**Repository:** https://github.com/BCHSI/philter-ucsf

## Resources
- https://informationcommons.ucsf.edu/sites/g/files/tkssra1026/f/wysiwyg/IC-495147816-070120-1723-16802.pdf
- https://ucsf.app.box.com/s/fh1tstj98p7z2sheego6o6as2lx9028x (I don't have access to this resource)

**Comment by tschaffter** [comment]
@yy6linda Who gave you the Box.com link (see above)?

**Comment by yy6linda** [comment]
Justin shared it with me. But the documents were removed already by people who created this link.

**Comment by jaeddy** [comment]
The MCW tool/service also appears to live in GitHub:
https://github.com/jayurbain/ctsi-mcw-deid

**EDIT** Here's the MCW org, with what I assume are more "official" repos:
https://github.com/MCW-BMI

**Comment by yy6linda** [comment]
Here is the link to the review of the two methods: https://docs.google.com/document/d/1xwebCoIt57iCYmmZFLfr96Da69-mD7Zepvsh1B0-Duc/edit

**Comment by tschaffter** [comment]
Links to resources for these two tools have been successfully compiled in this ticket.
