### ISSUE TITLE
Onboard developers of NLP deid methods

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#13]
Authors of NLP deid methods could provide valuable insights for the design of the continuous benchmarking project of NLP deid methods (e.g. format of input data, output data, information about computational resources needed to develop and run methods, etc.).

Suggested candidates:

- Bradley Taylor and George Kowalsky (De-identification X2)
- Jay Urbain (ctsi-mcw-deid, De-identification X2 may be the second iteration of ctsi-mcw-deid)

**Comment by tschaffter** [comment]
We are meeting with Bradley and George tomorrow.

**Comment by tschaffter** [comment]
For Bradley and George

- [x] Give them access to CD2H NLP Slack channel
- [ ] Add them to the NLP GH team (must be added to CD2H GH organization)
- [x] Collect their contact information (spreadsheet in Google folder)
- [x] Give them write access to NLP Google project folder

**Comment by tschaffter** [comment]
@tmdillon Bradley and George have filled in CD2H onboarding form. Will they be added automatically to CD2H GitHub Organization?

**Comment by tmdillon** [comment]
Yes that should automatically get them GitHub access.  I will check on it to be sure.

Tom

**Comment by gkowalski** [comment]
Tom, 

I don't seem to be added According to my profile ( which shows that orgs I'm part of ) .

**Comment by tmdillon** [comment]
Hi George – I’ll check on it.

**Comment by tschaffter** [comment]
@tmdillon 

George , Bradley and Yooree have not been added to the CD2H GitHub origanization yet. They have all filled in the onboarding form. How can we figure out what is blocking the onboarding process?

![image](https://user-images.githubusercontent.com/3056480/79006802-c6020080-7b0e-11ea-9189-e4f59d1816ff.png)

![image](https://user-images.githubusercontent.com/3056480/79006808-c9958780-7b0e-11ea-8e7d-00aafc0dda44.png)

![image](https://user-images.githubusercontent.com/3056480/79006817-cc907800-7b0e-11ea-94d5-86c0fae6bb72.png)

**Comment by tschaffter** [comment]
## Update

- Managed to add Yooree, George and Bradley (@btaylormcw) after contacting Andea Volz.
