### ISSUE TITLE
Catalog public and private datasets for NLP methods

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#14]
Identify the datasets that can be used for the continuous benchmarking project.

## Public datasets

Links to public datasets or datasets available upon request (e.g. I2b2 NLP challenge) can be shared with developers who want to benchmark their method.

- [National NLP Clinical Challenges (n2c2)](https://portal.dbmi.hms.harvard.edu/projects/n2c2-2014/) (needs to agree with DUA)

## Private datasets

Private datasets can be used for evaluation (not shared with participants).

- Add dataset

**Comment by tschaffter** [comment]
@yy6linda Are there any additional datasets in mind that can be added to the above list?

**Comment by tschaffter** [comment]
@BradleyTaylor @gkowalski This ticket is about inventorize public and private datasets, starting with yours. Could you share here the name and links to datasets you know about?

**Important:** This is a public repository. Please do not post sensitive information.

**Comment by yy6linda** [comment]
Name of the dataset | Current status | link
-- | -- | --
n2c2 2014: De-identification and Heart Disease Risk Factors Challenge | Requires DUA | https://portal.dbmi.hms.harvard.edu/projects/n2c2-2014/
N2c2 NLP research dataset | Requires DUA (accepted) | https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/
Global rare disease registry | Tech issues with the application form(under fixing according to the website) | https://portal.dbmi.hms.harvard.edu/projects/GRDR/
Commercial health insurance payer database | Send your request to Erica Meyer(Erica_Meyer@hms.harvard.edu), Program Manager. | https://portal.dbmi.hms.harvard.edu/projects/PAYERDB/
MIMIC III |CITI courses required | https://mimic.physionet.org/mimictables/noteevents/

**Comment by tschaffter** [comment]
### Update

@yy6linda 

- Identify if the DUA accepted by Justin also covers the dataset `n2c2-2014`
- Deep dive into each of the above datasets to identify
  - The protocol used to annotate sensitive information
  - The format of the gold standard
