### ISSUE TITLE
Get access to NCATS resources

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#15]
The reason we need access to an NCATS EC2 is to prepare an environment for the continuous benchmarking project that will have access to private datasets.

@yy6linda and @jguinney have already filled in a request form.

@tmdillon: You mentioned that some information were missing from the request form. Do you now have all the information needed?

**Comment by tmdillon** [comment]
Thomas

Your request and several others are blocked by some CD2H-NCATS process / project management issues.   As soon as the issues get resolved I will let you know.
Tom

**Comment by tschaffter** [comment]
## Update

- George had a meeting on April 13 with NCATS
  - Move NLP de-id method code base to CD2H GH repo?
  - Configure Jenkins integration on GH repo

**Comment by tschaffter** [comment]
@gkowalski has now access to the NCATS server
