### ISSUE TITLE
Define primary and secondary scoring metrics

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#16]
At least two metrics a required, the second being used as a tie breaker.

## Depends on

- #18 
- #12

**Comment by tschaffter** [comment]
@yy6linda Can you give a short description of the performance metrics used in the n2c2 2014 Challenge?

**Comment by tschaffter** [comment]
https://github.com/MUSC-TBIC/etude-engine

**Comment by yy6linda** [comment]
The i2b2 challenge used precision, recall and F1 score as the matrices for assessment. The gold standard is generated based on the annotation done by the data curator.
