### ISSUE TITLE
Define NLP De-id API

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#24]
- [x] Create GH repo
- [x] Seed it with George current implementation
- [ ] Add endpoints and models

**Comment by gkowalski** [comment]
This was my first crack at an API to get the ball rolling : https://app.swaggerhub.com/apis-docs/gkowalski/test/1.0.0#/ Design was to meet the current MCW-DEID process which talks directly to a database . Moving the upload of patient data in a separate API Call  does make more sense.

**Comment by tschaffter** [comment]
https://github.com/data2health/nlp-deid-service-schemas

**Comment by tschaffter** [comment]
This task has become too broad. It will be replaced by smaller and more descriptive tasks.
