### ISSUE TITLE
Investigate NLM-Scrubber

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#37]
https://scrubber.nlm.nih.gov/

**Comment by tschaffter** [comment]
@gkowalski Could you review this method and share with Yao and I:

- How this method work
  - What information does this method relies on (useful to the design of our input specifications)
  - What is the format of the output (useful to the design of or output specifications) 
- How does it differ from your method

**Comment by gkowalski** [comment]
Where should I document this ? I have my review completed in a Google Doc.

**Comment by tschaffter** [comment]
The review is available as a Google doc [here](https://docs.google.com/document/d/16n3zfYzIt-GeuC0udjqScsUYvnNp8uucoMffmA9KheM/edit?ts=5f2320e8).
