### ISSUE TITLE
Review Amazon Comprehend Medical

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#38]
>NLP enables the recognition and prediction of diseases based on electronic health records and patient’s own speech. This capability is being explored in health conditions that go from cardiovascular diseases to depression and even schizophrenia. For example, Amazon Comprehend Medical is a service that uses NLP to extract disease conditions, medications and treatment outcomes from patient notes, clinical trial reports and other electronic health records.

https://aws.amazon.com/comprehend/medical/

**Comment by tschaffter** [comment]
## Resources

- [AWS re:Invent 2019: Insights into patient health with Amazon Comprehend Medical (video)](https://youtu.be/x9HD0tT6pDk)
- [AI-Powered Health Data Masking (AWS Solution with code)](https://aws.amazon.com/solutions/ai-powered-health-data-masking/)
- [Extract and visualize clinical entities using Amazon Comprehend Medical (stack)](https://aws.amazon.com/blogs/machine-learning/extract-and-visualize-clinical-entities-using-amazon-comprehend-medical/)
- [aws-samples/amazon-comprehend-medical-fhir-integration (GitHub)](https://github.com/aws-samples/amazon-comprehend-medical-fhir-integration)

**Comment by tschaffter** [comment]
@cascadianblue If you have time, would you also like to have a look at Amazon Comprehend Medical? I've listed a few resources of interest above.

**Comment by boyleconnor** [comment]
@tschaffter I think we finished this one off, right?
