### ISSUE TITLE
Review Method 2: UCSFPhilter

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#4]
Review Method 2: UCSFPhilter

**Comment by yy6linda** [comment]
Here is the review document. https://docs.google.com/document/d/1xwebCoIt57iCYmmZFLfr96Da69-mD7Zepvsh1B0-Duc/edit?usp=sharing

**Comment by tschaffter** [comment]
Review: https://docs.google.com/document/d/1JX7eykr7Rt66I9BtTesA6SPGbmixRZokpRgbvQ8WpJo/edit
