### ISSUE TITLE
Review two annotation tools used by Mayo Clinic

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#49]
Justin said:

> FYI, on call with Hongfang discussing text. Here are 2 popular ones that might be of interest to you:

- [x] https://brat.nlplab.org/
- [x] http://keighrim.github.io/mae-annotation/ 

## Task

- Most importantly we are interested in identifying the ontology / data schema used by these two tools to annotate clinical notes.
- Create 2-5 slides that summarize how each method work

**Comment by ymnliu** [comment]
A brief introduction can be found at https://docs.google.com/presentation/d/1h86gCmVVmtq4FbBCXXYyE38tMCoOJwyNc42VmAmKf3E/edit?usp=sharing
