### ISSUE TITLE
Review EMERSE

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#56]
Tom Dillon contact me to connect me with David Hanauer from the University of Michigan.

> David would like to become more actively involved with CD2H.  David works with an application called EMERSE (http://project-emerse.org/about.html#:~:text=EMERSE%20is%20similar%20to%20natural%20language%20processing%20%28NLP%29%2C,effort%20is%20required%20to%20get%20started%20with%20it.)

> Since EMERSE is similar to an NLP process, I thought that you may be able to point David to a CD2H team that would may have some common interests.    If I can help with anything let me know.

## Task

- Review the documentation and demo available on EMERSE website
- Summarize important information about EMERSE on 3-5 slides

**Comment by ymnliu** [comment]
Hi @tschaffter, when would you need this?

**Comment by tschaffter** [comment]
Either this Tuesday or next Tuesday would be great

**Comment by tschaffter** [comment]
@ymnliu Did you present EMERSE or CLAMP last Tuesday?

**Comment by ymnliu** [comment]
@tschaffter I reviewed EMERSE last week. I will go over CLAMP shortly.
