### ISSUE TITLE
Evaluate the performance of Google de-id service for the date annotation task

### ISSUE THREAD

**Issue by tschaffter** [data2health/nlp-sandbox#64]
As we are nearing the launch of the NLP Sandbox, I like us to evaluate the performance of Google service in a few of our benchmarking categories. The first category that we are going to support is the benchmarking of methods that can detect "Dates" (e.g. "27/09/2010", "2010-09-27", "Monday", etc.) in clinical notes. At launch time, we would then display the performance of Google service in the leaderboard table for this category.

Here are more information about the task:

Given a clinical note as input, what we need is the location of the date string in the text detected by Google service. For each date annotation detected, we need the position of the first character (property `start`) as well as the number of characters included in the date string (property `length`). The format of this date annotation object is defined here if you are familiar with YAML / OpenAPI.

[Annotation.yaml](https://github.com/data2health/nlp-sandbox-schemas/blob/develop/openapi/commons/components/schemas/Annotation.yaml)
[DateAnnotation.yaml](https://github.com/data2health/nlp-sandbox-schemas/blob/develop/openapi/commons/components/schemas/DateAnnotation.yaml) (extends Annotation.yaml)

Here are the steps to perform:

1. Look at Google de-id service documentation if it can return the requested information (see above). If not, write a script that can extract this information from the anonymized clinical note returned by the service.

2. Download the i2b2 clinical notes and process them using Google service. Note that these notes have been previously anonymized and do not contain PHI. However, these data are not public and so they should not be hosted in a public repository (e.g. GitHub).

3. Process the responses received by Google to generate DateAnnotation objects as defined above.

Yao will then compare the DateAnnotation objects to our gold standard to evaluate the performance of Google de-id service (F1 score, Precision, Recall).

**Comment by tschaffter** [comment]
@cascadianblue 

> I wouldn't be mandatory for me to extract the date format (e.g. MM-DD vs. DD-MM-YYYY) from the text, right?
Correct, we don't need to get this information from Google. We only want the location of the date string in the text.

> I could use the "character mask" transformation 

This sounds like a good strategy. We should be able to then use it to evaluate the performance of Google de-id service to detect person names - though we are currently not able to provide a patient object (not available in our dataset) to Google along the clinical note - and other PHIs. Therefore, can you write your code in a generic way (mainly when you pick names for your variables, e.g. use a variable phi_mask_character instead of date_mask_character). No need to design the script so that we can extract the information we need in a single "run". For each type of PHI information that we want to extract (date, person name, etc.) we will do another run, i.e. send again the clinical note to Google service with just changing a configuration setting to let Google know what it should detect.

**Comment by boyleconnor** [comment]
@tschaffter this one is done, right?

**Comment by tschaffter** [comment]
Yes, thanks!
